name: 'Run Player Tests'
description: 'Run player tests'
inputs:
  test-name:
    description: 'What test to run'
    required: true
  url-bundle:
    description: 'JSON encoded string of live, vod and clip url'
    required: true
outputs:
  passed:
    description: "If the test passed or not"
    value: ${{ steps.test-runner.outputs.passed }}
runs:
  using: "composite"
  steps:
    - id: test-runner
      run: ./player.sh "${{ inputs.test-name }}" << "${{ inputs.url-bundle }}"
      shell: bash
    - run: echo "passed=$?" >> $GITHUB_OUTPUT
      shell: bash
