name: 'Run Player Tests'
description: 'Run player tests'
inputs:
  test-name:
    description: 'What test to run'
    required: true
  live-url:
    description: 'Live Twitch stream url'
    required: true
  vod-url:
    description: 'Twitch VOD url'
    required: true
  clip-url:
    description: 'Twitch Clip url'
    required: true
outputs:
  passed:
    description: "If the test passed or not"
    value: ${{ steps.test-runner.outputs.passed }}
runs:
  using: "composite"
  steps:
    - id: test-runner
      run: ./player.sh "${{ inputs.test-name }}" ${{ inputs.live-url }} ${{ inputs.vod-url }} ${{ inputs.clip-url }}
      shell: bash
    - run: echo "passed=$?" >> $GITHUB_OUTPUT
      shell: bash
