name: 'Run Fuzzer'
description: 'Run fuzzing script'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  url-bundle:
    description: "JSON string url bundle"
    value: ${{ steps.fuzzy-input-generator.outputs.url-bundle }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: fuzzy-input-generator
      run: echo "url-bundle=$(python3 generate-fuzzy-inputs.py)" >> $GITHUB_OUTPUT
      shell: bash
