name: 'Run Fuzzer'
description: 'Run fuzzing script'
outputs:
  live-web:
    value: ${{ steps.fuzzy-input-generator.outputs.live-web }}
  vod-web:
    value: ${{ steps.fuzzy-input-generator.outputs.vod-web }}
  clip-web:
    value: ${{ steps.fuzzy-input-generator.outputs.clip-web }}
runs:
  using: "composite"
  steps:
    - id: fuzzy-input-generator
      run: python3 generate-fuzzy-inputs.py
      shell: bash
    - name: 'Echo GITHUB_OUTPUT'
      run: echo $GITHUB_OUTPUT
      shell: bash
