on: [push]

jobs:
  fuzzy_test_runner:
    runs-on: ubuntu-latest
    name: run fuzzy tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - id: generate-fuzzy-inputs
        uses: ./.github/actions/run-fuzzer
      - id: run-player-tests
        uses: ./.github/actions/run-player
        with:
          test-name: 'web e2e'
      - if: always()
        run: echo url-bundle ${{ steps.generate-fuzzy-inputs.outputs.url-bundle }}
        shell: bash
