on: [push]

jobs:
  fuzzy_test_runner:
    runs-on: ubuntu-latest
    name: run fuzzy tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - id: generate-fuzzy-inputs
        uses: ./.github/actions/run-fuzzer
      - id: run-player-tests
        uses: ./.github/actions/run-player
        with:
          test-name: 'web e2e'
          live-url: ${{ steps.generate-fuzzy-inputs.outputs.live-web }}
          vod-url: ${{ steps.generate-fuzzy-inputs.outputs.vod-web }}
          clip-url: ${{ steps.generate-fuzzy-inputs.outputs.clip-web }}
      - name: Analyze results
        if: always()
        run: echo test results ${{ steps.run-player-tests.outputs.passed }}
        shell: bash
